### ISSUE TITLE
Shlex split breaks windows paths

### ISSUE THREAD

**Issue by dropthemic** [ponty/EasyProcess#12]
When you set the cmd argument to a string, EasyProcess will call split_command to break out the cmd from its arguments.

On Windows environment, split_command will return invalid command.

For example:
`
split_command('c:\\temp\\a.exe someArg')
#returns ['c:tempa.exe', 'someArg']
`

The fix seems to be set the posix argument in shlex (see https://github.com/maebert/jrnl/issues/348)

https://github.com/ponty/EasyProcess/blob/master/easyprocess/unicodeutil.py#L44
`cmd = shlex.split(cmd, posix='win' not in sys.platform)
`

**Comment by ponty** [comment]
Thanks!
