### ISSUE TITLE
Include preexec_fn in Popen call

### ISSUE THREAD

**Issue by guaguanco** [ponty/EasyProcess#15]
Adding the `preexec_fn` argument to `EasyProcess` and passing it to the `Popen` call would be useful, e.g. for setting limits within the subprocess

**Comment by ponty** [comment]
`preexec_fn` has a warning in the doc:
https://docs.python.org/3/library/subprocess.html#popen-constructor
"Warning:The preexec_fn parameter is not safe to use in the presence of threads in your application."

So `preexec_fn`  seems to be advanced usage which is out of scope for `EasyProcess`.
This lib is intended only for simple and safe cases.
