### ISSUE TITLE
Tests use literal "python" which defaults to python2

### ISSUE THREAD

**Issue by jayvdb** [ponty/EasyProcess#18]
I am runnings tests of lots of packages in VMs without a `python` executable, and there are lots of tests failing for EasyProcess , under examples.

The quick fix is to use `sys.executable`, and that appears to have been done in `tests/coverage` .

However something like `EasyProcess('python -c "print 3"')` would need to be `EasyProcess('"' + sys.executable + '" -c "print 3"')` to account for whitespace in the path, especially for Windows.

**Comment by ponty** [comment]
Examples were created for Linux, and they should be very simple.
The solution is then to disable these tests for Windows.

**Comment by ponty** [comment]
All tests should run on Windows, MacOS and Linux. 
https://travis-ci.org/github/ponty/EasyProcess

**Comment by ponty** [comment]
Resolved.
