### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by gergelyk** [ponty/EasyProcess#25]
Nice library, but a few features feel missing:

- raise an exception when return code is different than 0 (or user-defined value(s)).
- support providing data to stdin.
- support connecting stdout of one command to stdin of another one.

**Comment by ponty** [comment]
The library is planned to be simple, that's why pipes are not supported. (points 2 and 3)

Point 1 is easy to implement:
```py
r = EasyProcess(["python", "--version"]).call().return_code
if r != 0:
    raise ValueError("my error")
```

**Comment by gergelyk** [comment]
Thanks for explanations.
