### ISSUE TITLE
Doesn't report correct version to pip

### ISSUE THREAD

**Issue by tgs** [ponty/EasyProcess#6]
When I run `pip install EasyProcess`, it downloads EasyProcess-0.1.6 from PyPI, and installs it.  But then when I run `pip freeze`, it says `EasyProcess==0.0.0`.

Maybe it's fixed by the new version of Versioneer you just added, I didn't try.  Anyway, this really confuses Pip sometimes.

**Comment by ponty** [comment]
Can you provide more details?
I can not reproduce this error.
The latest PyPI version (0.1.6) doesn't have Versioneer at all.
Are you testing the git version?

**Comment by tgs** [comment]
Ah, I didn't notice that Versioneer was new.

I'm using Python 3.3.  I manually download EasyProcess-0.1.6.tar.gz from PyPI, extract it, cd to the directory.

```
$ egrep ^Version EasyProcess.egg-info/PKG-INFO
Version: 0.1.6

$ python3 setup.py egg_info
running egg_info
writing EasyProcess.egg-info/PKG-INFO
writing top-level names to EasyProcess.egg-info/top_level.txt
writing dependency_links to EasyProcess.egg-info/dependency_links.txt
reading manifest file 'EasyProcess.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'CHANGES*'
no previously-included directories found matching 'docs/_build'
writing manifest file 'EasyProcess.egg-info/SOURCES.txt'

$ egrep ^Version EasyProcess.egg-info/PKG-INFO
Version: 0.0.0
```

I think the problem is in `read_project_version` - I looked and the `__version__` variable is still None at the end of that function when it's run under Python 3.

This makes it hard to build a wheel version of the package - the wheel claims to be version 0.0.0.

**Comment by Ashald** [comment]
That's pretty important to us. Can we expect fix in near future? Or if you don't have a time we can contribute a fix and create a PR.

**Comment by ponty** [comment]
I could reproduce the bug with python3. No error withon python2.

**Comment by ponty** [comment]
Please test the latest version (0.1.9)

**Comment by tgs** [comment]
Works for me - thank you!
