### ISSUE TITLE
EasyProcess.__repr__() improvement

### ISSUE THREAD

**Issue by molecular** [ponty/EasyProcess#9]
firstly, thanks for a cool easy process helper

please change **init**.py line 118 from 
`msg = '<%s cmd_param=%s cmd=%s oserror=%s returncode=%s stdout="%s" stderr="%s" timeout=%s>' % (` to 
`msg = '<%s cmd_param=%s cmd=%s oserror=%s return_code=%s stdout="%s" stderr="%s" timeout_happened=%s>' % (`
("returncode" => "return_code", "timeout" => "timeout_happened")

that way, it's easier for people to guess the name of the return_code and timeout_happened variable.

also, "timeout_happened" isn't documented at all (no example, no mention of it) in readme.md

**Comment by ponty** [comment]
Done!
Thanks for the comment. You can also send pull requests with improvements on documentation or code.

**Comment by molecular** [comment]
Hi, thanks a lot!

Hint about pull requests received.

I would like to make a small donation to you in bitcoin, if that is possible?

**Comment by ponty** [comment]
Thanks for your offer. 

My bitcoin address:  124fj6NXsKmLhjNqJyc8FMcdwgiCwCfLPZ

**Comment by molecular** [comment]
just sent €15 in BTC. Thanks again for EasyProcess.

**Comment by ponty** [comment]
Thanks for the support!
